services:
  web-app-frontend:
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: .
          target: /usr/src/nuxt-app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
